require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FileAttachmentsController do

  # This should return the minimal set of attributes required to create a valid
  # FileAttachment. As you add validations to FileAttachment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FileAttachmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all file_attachments as @file_attachments" do
      file_attachment = FileAttachment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:file_attachments).should eq([file_attachment])
    end
  end

  describe "GET show" do
    it "assigns the requested file_attachment as @file_attachment" do
      file_attachment = FileAttachment.create! valid_attributes
      get :show, {:id => file_attachment.to_param}, valid_session
      assigns(:file_attachment).should eq(file_attachment)
    end
  end

  describe "GET new" do
    it "assigns a new file_attachment as @file_attachment" do
      get :new, {}, valid_session
      assigns(:file_attachment).should be_a_new(FileAttachment)
    end
  end

  describe "GET edit" do
    it "assigns the requested file_attachment as @file_attachment" do
      file_attachment = FileAttachment.create! valid_attributes
      get :edit, {:id => file_attachment.to_param}, valid_session
      assigns(:file_attachment).should eq(file_attachment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FileAttachment" do
        expect {
          post :create, {:file_attachment => valid_attributes}, valid_session
        }.to change(FileAttachment, :count).by(1)
      end

      it "assigns a newly created file_attachment as @file_attachment" do
        post :create, {:file_attachment => valid_attributes}, valid_session
        assigns(:file_attachment).should be_a(FileAttachment)
        assigns(:file_attachment).should be_persisted
      end

      it "redirects to the created file_attachment" do
        post :create, {:file_attachment => valid_attributes}, valid_session
        response.should redirect_to(FileAttachment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved file_attachment as @file_attachment" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:file_attachment => {}}, valid_session
        assigns(:file_attachment).should be_a_new(FileAttachment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:file_attachment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested file_attachment" do
        file_attachment = FileAttachment.create! valid_attributes
        # Assuming there are no other file_attachments in the database, this
        # specifies that the FileAttachment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FileAttachment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => file_attachment.to_param, :file_attachment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested file_attachment as @file_attachment" do
        file_attachment = FileAttachment.create! valid_attributes
        put :update, {:id => file_attachment.to_param, :file_attachment => valid_attributes}, valid_session
        assigns(:file_attachment).should eq(file_attachment)
      end

      it "redirects to the file_attachment" do
        file_attachment = FileAttachment.create! valid_attributes
        put :update, {:id => file_attachment.to_param, :file_attachment => valid_attributes}, valid_session
        response.should redirect_to(file_attachment)
      end
    end

    describe "with invalid params" do
      it "assigns the file_attachment as @file_attachment" do
        file_attachment = FileAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_attachment.to_param, :file_attachment => {}}, valid_session
        assigns(:file_attachment).should eq(file_attachment)
      end

      it "re-renders the 'edit' template" do
        file_attachment = FileAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_attachment.to_param, :file_attachment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested file_attachment" do
      file_attachment = FileAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => file_attachment.to_param}, valid_session
      }.to change(FileAttachment, :count).by(-1)
    end

    it "redirects to the file_attachments list" do
      file_attachment = FileAttachment.create! valid_attributes
      delete :destroy, {:id => file_attachment.to_param}, valid_session
      response.should redirect_to(file_attachments_url)
    end
  end

end
