require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PermissionForFoldersController do

  # This should return the minimal set of attributes required to create a valid
  # PermissionForFolder. As you add validations to PermissionForFolder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PermissionForFoldersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all permission_for_folders as @permission_for_folders" do
      permission_for_folder = PermissionForFolder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:permission_for_folders).should eq([permission_for_folder])
    end
  end

  describe "GET show" do
    it "assigns the requested permission_for_folder as @permission_for_folder" do
      permission_for_folder = PermissionForFolder.create! valid_attributes
      get :show, {:id => permission_for_folder.to_param}, valid_session
      assigns(:permission_for_folder).should eq(permission_for_folder)
    end
  end

  describe "GET new" do
    it "assigns a new permission_for_folder as @permission_for_folder" do
      get :new, {}, valid_session
      assigns(:permission_for_folder).should be_a_new(PermissionForFolder)
    end
  end

  describe "GET edit" do
    it "assigns the requested permission_for_folder as @permission_for_folder" do
      permission_for_folder = PermissionForFolder.create! valid_attributes
      get :edit, {:id => permission_for_folder.to_param}, valid_session
      assigns(:permission_for_folder).should eq(permission_for_folder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PermissionForFolder" do
        expect {
          post :create, {:permission_for_folder => valid_attributes}, valid_session
        }.to change(PermissionForFolder, :count).by(1)
      end

      it "assigns a newly created permission_for_folder as @permission_for_folder" do
        post :create, {:permission_for_folder => valid_attributes}, valid_session
        assigns(:permission_for_folder).should be_a(PermissionForFolder)
        assigns(:permission_for_folder).should be_persisted
      end

      it "redirects to the created permission_for_folder" do
        post :create, {:permission_for_folder => valid_attributes}, valid_session
        response.should redirect_to(PermissionForFolder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved permission_for_folder as @permission_for_folder" do
        # Trigger the behavior that occurs when invalid params are submitted
        PermissionForFolder.any_instance.stub(:save).and_return(false)
        post :create, {:permission_for_folder => {}}, valid_session
        assigns(:permission_for_folder).should be_a_new(PermissionForFolder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PermissionForFolder.any_instance.stub(:save).and_return(false)
        post :create, {:permission_for_folder => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested permission_for_folder" do
        permission_for_folder = PermissionForFolder.create! valid_attributes
        # Assuming there are no other permission_for_folders in the database, this
        # specifies that the PermissionForFolder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PermissionForFolder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => permission_for_folder.to_param, :permission_for_folder => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested permission_for_folder as @permission_for_folder" do
        permission_for_folder = PermissionForFolder.create! valid_attributes
        put :update, {:id => permission_for_folder.to_param, :permission_for_folder => valid_attributes}, valid_session
        assigns(:permission_for_folder).should eq(permission_for_folder)
      end

      it "redirects to the permission_for_folder" do
        permission_for_folder = PermissionForFolder.create! valid_attributes
        put :update, {:id => permission_for_folder.to_param, :permission_for_folder => valid_attributes}, valid_session
        response.should redirect_to(permission_for_folder)
      end
    end

    describe "with invalid params" do
      it "assigns the permission_for_folder as @permission_for_folder" do
        permission_for_folder = PermissionForFolder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PermissionForFolder.any_instance.stub(:save).and_return(false)
        put :update, {:id => permission_for_folder.to_param, :permission_for_folder => {}}, valid_session
        assigns(:permission_for_folder).should eq(permission_for_folder)
      end

      it "re-renders the 'edit' template" do
        permission_for_folder = PermissionForFolder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PermissionForFolder.any_instance.stub(:save).and_return(false)
        put :update, {:id => permission_for_folder.to_param, :permission_for_folder => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested permission_for_folder" do
      permission_for_folder = PermissionForFolder.create! valid_attributes
      expect {
        delete :destroy, {:id => permission_for_folder.to_param}, valid_session
      }.to change(PermissionForFolder, :count).by(-1)
    end

    it "redirects to the permission_for_folders list" do
      permission_for_folder = PermissionForFolder.create! valid_attributes
      delete :destroy, {:id => permission_for_folder.to_param}, valid_session
      response.should redirect_to(permission_for_folders_url)
    end
  end

end
